### PR TITLE
Fixed MB-1729. Added csrf token to POST method in more button in queue browse page

### PR DESCRIPTION
**Pull request by sajinidesilva**

### CODE REVIEW

**Comment by sajinidesilva** [comment]
Fixed https://wso2.org/jira/browse/MB-1729

**Comment by sdkottegoda** [comment]
This will only resolve the problem in the queue browse page. If we have other pages that use forms, the issue will still be there in those. As a resolution we can modify the "csrfPrevention.js" and use the modified .js as explained in "CSRF is token not injected to some of the elements of the web page by 'csrfPrevention.js'"

**Comment by sajinidesilva** [comment]
@sdkottegoda It will be a security vulnerability then. I think we should correct all the forms which are using POST requests like this.

**Comment by sdkottegoda** [comment]
Addresses the issue reported at https://wso2.org/jira/browse/MB-1788 as well

**Pull request merged**
